import { Hero } from "@/components/Hero";
import { LoadingScreen } from "@/components/LoadingScreen";
import { LogoMarquee } from "@/components/LogoMarquee";
import { Stats } from "@/components/Stats";
import { Testimonials } from "@/components/Testimonials";
import { Pricing } from "@/components/Pricing";
import { FAQ } from "@/components/FAQ";
import { CTA } from "@/components/CTA";
import { Footer } from "@/components/Footer";
import { AboutSection } from "@/components/AboutSection";
import { CoverflowCarousel } from "@/components/ui/coverflow-carousel";
import { motion } from "framer-motion";

const SLIDES = [
  {
    title: "AI Phishing Defense",
    category: "Email & Messaging",
    src: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80",
    description: "Neutralize hyper-personalized spear phishing generated by LLMs before delivery.",
  },
  {
    title: "Deepfake Detection",
    category: "Identity & Media",
    src: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80",
    description: "Authenticate voice calls, video meetings, and executive media in real time.",
  },
  {
    title: "Autonomous Response",
    category: "SOC Automation",
    src: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1200&q=80",
    description: "Isolate compromised endpoints and revoke tokens in sub-200ms without human intervention.",
  },
  {
    title: "Zero-Day Exploit Shield",
    category: "Endpoint & Cloud",
    src: "https://images.unsplash.com/photo-1510511459019-5dda7724fd87?auto=format&fit=crop&w=1200&q=80",
    description: "Behavioral runtime sandboxing that halts novel payloads before execution.",
  },
  {
    title: "Compliance & Audit Trail",
    category: "Governance",
    src: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
    description: "Continuous posture reporting aligned to SOC2, ISO 27001, and NIST AI RMF frameworks.",
  },
];

export function Home() {
  return (
    <div className="flex flex-col">
      <LoadingScreen />
      <Hero />

      <div className="relative z-10 bg-background">
        <LogoMarquee />
        <Stats />

        <section id="features" className="bg-secondary/30 py-24 sm:py-32">
          <div className="mx-auto mb-16 max-w-7xl px-6 text-center lg:px-8">
            <div className="mx-auto max-w-2xl">
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.8 }}
              >
                <p className="text-sm font-semibold uppercase tracking-widest text-primary">01 / Platform</p>
                <h2 className="mt-4 font-display text-4xl leading-tight text-foreground sm:text-5xl">
                  One console for every surface attackers target.
                </h2>
              </motion.div>
              <motion.p
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.8, delay: 0.2 }}
                className="mt-6 text-lg leading-relaxed text-muted-foreground"
              >
                Explore how Crest unifies detection across communication, identity, endpoints, and cloud infrastructure.
              </motion.p>
            </div>
          </div>
          <CoverflowCarousel slides={SLIDES} showCaption showNavigation showPagination autoPlay autoPlayInterval={4500} />
        </section>

        <Testimonials />
        <Pricing />
        <AboutSection />
        <FAQ />
        <CTA />
        <Footer />
      </div>
    </div>
  );
}
