import { Hero } from "@/components/Hero";
import { LoadingScreen } from "@/components/LoadingScreen";
import { LogoMarquee } from "@/components/LogoMarquee";
import { Stats } from "@/components/Stats";
import { Testimonials } from "@/components/Testimonials";
import { Pricing } from "@/components/Pricing";
import { FAQ } from "@/components/FAQ";
import { CTA } from "@/components/CTA";
import { Footer } from "@/components/Footer";
import { AboutSection } from "@/components/AboutSection";
import { CoverflowCarousel } from "@/components/ui/coverflow-carousel";
import { ScrollFloat } from "@/components/ScrollFloat";
import { ScrollReveal } from "@/components/ScrollReveal";

const SLIDES = [
  {
    title: "AI Phishing Defense",
    category: "Email & Messaging",
    src: "/card-artwork.jpg",
    description: "Neutralize hyper-personalized spear phishing generated by LLMs before delivery.",
  },
  {
    title: "Deepfake Detection",
    category: "Identity & Media",
    src: "/card-artwork.jpg",
    description: "Authenticate voice calls, video meetings, and executive media in real time.",
  },
  {
    title: "Autonomous Response",
    category: "SOC Automation",
    src: "/card-artwork.jpg",
    description: "Isolate compromised endpoints and revoke tokens in sub-200ms without human intervention.",
  },
  {
    title: "Zero-Day Exploit Shield",
    category: "Endpoint & Cloud",
    src: "/card-artwork.jpg",
    description: "Behavioral runtime sandboxing that halts novel payloads before execution.",
  },
  {
    title: "Compliance & Audit Trail",
    category: "Governance",
    src: "/card-artwork.jpg",
    description: "Continuous posture reporting aligned to SOC2, ISO 27001, and NIST AI RMF frameworks.",
  },
];

export function Home() {
  return (
    <div className="flex flex-col">
      <LoadingScreen />
      <Hero />

      <div className="relative z-10 bg-background">
        <LogoMarquee />
        <Stats />

        <section id="features" className="bg-secondary/30 py-24 sm:py-32">
          <div className="mx-auto mb-16 max-w-7xl px-6 text-center lg:px-8">
            <div className="mx-auto max-w-2xl">
              <p className="text-sm font-semibold uppercase tracking-widest text-primary">01 / Platform</p>
              <ScrollFloat
                containerClassName="mt-4 font-display text-4xl leading-tight text-foreground sm:text-5xl"
                animationDuration={0.85}
                ease="back.inOut(2)"
                scrollStart="top bottom-=12%"
                scrollEnd="bottom center+=8%"
                stagger={0.022}
              >
                One console for every surface attackers target.
              </ScrollFloat>
              <ScrollReveal
                containerClassName="mt-6"
                textClassName="text-lg leading-relaxed text-muted-foreground"
                baseOpacity={0.12}
                baseRotation={2}
                blurStrength={6}
                rotationEnd="bottom center+=8%"
                wordAnimationEnd="bottom center+=8%"
              >
                Explore how Crest unifies detection across communication, identity, endpoints, and cloud infrastructure.
              </ScrollReveal>
            </div>
          </div>
          <CoverflowCarousel slides={SLIDES} showCaption showNavigation showPagination autoPlay autoPlayInterval={4500} />
        </section>

        <Testimonials />
        <Pricing />
        <AboutSection />
        <FAQ />
        <CTA />
        <Footer />
      </div>
    </div>
  );
}
